[package]
name = "gpio-toggle"
version = "1.0.0"
authors = ["Kai-Chieh Ku <kjackie@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-files = "0.2.1"
gpio-cdev = "0.2"
once_cell = "1.3.1"
quicli = "0.4"
structopt = "0.2"
